# Generated by Django 2.1.1 on 2018-10-01 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181001_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companylist',
            old_name='compnay_name',
            new_name='company_name',
        ),
    ]
