# Generated by Django 2.1.2 on 2018-10-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181001_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companylist',
            name='company_name',
            field=models.CharField(max_length=20),
        ),
    ]
